
node('jenkins-agent-docker-sg2042') {
    stage("checkout scm") {
        cleanWs()
        checkout scm
    }

    stage("properties") {
        load('RVCI/RVCK/config.groovy')
        properties([
            parameters(kernel_build_params_keys.collect {
                all_params[it]
            })
        ])
    }
    
    if(params.size() != 0) {
        stage("build") {
            timestamps {
                try {
                    // 执行构建脚本
                    sh 'bash RVCI/RVCK/rvck-kernel-build/run.sh'
                    
                    // 更新github状态
                    build wait: false, job: 'gh_actions', parameters: [
                        string(name: 'REPO', value: REPO),
                        string(name: 'ISSUE_ID', value: pr_id),
                        string(name: 'COMMENT_CONTENT', value: 'Kernel build success!'),
                        string(name: 'SET_LABEL', value: 'kernel_build_succeed,lava_checking'),
                    ]
                    
                    // 触发lava测试
                    lava_trigger_params = lava_trigger_params_keys.findAll {
                        params.containsKey(it)
                    }.collect {
                        string(name: it, value: params[it])
                    }

                    build wait: false, job: 'rvck-lava-trigger', parameters: lava_trigger_params + [
                        string(name: 'rootfs_download_url', value: readFile('evnironment.temp/rootfs_download_url')),
                        string(name: 'kernel_download_url', value: readFile('evnironment.temp/kernel_download_url')),
                    ]
                } catch (err) {
                    build wait: true, job: 'gh_actions', parameters: [
                        string(name: 'REPO', value: REPO),
                        string(name: 'ISSUE_ID', value: pr_id),
                        string(name: 'COMMENT_CONTENT', value: "Kernel build failed! log:${BUILD_URL}consoleFull"),
                        string(name: 'SET_LABEL', value: 'kernel_build_failed'),
                    ]

                    currentBuild.result = 'FAILURE'
                    throw err
                }
            }
        }
    }
    
}
