
node("jenkins-agent-lavacli-docker") {
    stage("checkout scm") {
        cleanWs()
        checkout scm
    }

    stage("properties") {
        def config = load('RVCI/RVCK/config.groovy')
        // 设置参数化构建
        properties([
            parameters(config.lava_trigger_params_keys.collect {
                config.all_params[it]
            }),
        ])
    } 
    if(params.size() != 0) {
        // 执行构建
        stage("init workspace") {
            checkout scmGit(
                userRemoteConfigs: [[url: 'https://github.com/RVCK-Project/lavaci.git']],
                branches: [[name: 'main']],
                extensions: [cloneOption(depth: 1, noTags: true, reference: '', shallow: true, timeout: 5)],
            )
        }
    
        stage("lava check") {
            timestamps {
                try {
                    withCredentials([usernameColonPassword(credentialsId: 'dd2c86ed-f19e-445b-9fc8-5d2c2b23ecd2', variable: 'lava_admin_token')]) {
                        sh 'bash RVCI/RVCK/rvck-lava-trigger/run.sh'
                    }
                    build wait: false, job: 'gh_actions', parameters: [
                        string(name: 'REPO', value: params.REPO),
                        string(name: 'ISSUE_ID', value: params.ISSUE_ID),
                        string(name: 'SET_LABEL', value: 'lava_check_pass'),
                        string(name: 'COMMENT_CONTENT', value: readFile('COMMENT_CONTENT')),
                    ]
                } catch (err) {
                    build wait: false, job: 'gh_actions', parameters: [
                        string(name: 'REPO', value: params.REPO),
                        string(name: 'ISSUE_ID', value: params.ISSUE_ID),
                        string(name: 'SET_LABEL', value: 'lava_check_fail'),
                        string(name: 'COMMENT_CONTENT', value: readFile('COMMENT_CONTENT')),
                    ]
                    currentBuild.result = 'FAILURE'
                    throw err
                }
            }
        }
    }
}