
node('jenkins-agent-gh-docker') {
    stage('checkout scm') {
        cleanWs()
        checkout scm
    }

    def isAnyParams = params.size() != 0

    stage("properties") {
        load('RVCI/RVCK/config.groovy')
        properties([
            parameters(gh_actions_params_keys.collect {
                allParams[it]
            }),
        ])
    }

    if(params.size() != 0) {
        stage('gh actions') {
            withCredentials([string(credentialsId: 'rvck_gh_token', variable: 'GH_TOKEN')]) {
                sh 'bash RVCI/RVCK/gh_actions/run.sh'
            }
        }
    }
}
